name: Build OddJobs React Native App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose Node.js version compatible with React Native

      - name: Install dependencies
        run: |
          npm install
          npx pod-install  # For iOS projects using CocoaPods (only on macOS jobs)

  build:
    needs: install
    runs-on: ubuntu-latest  # You may need macos-latest for iOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build project
        run: npm run build  # Replace with any specific build command for React Native, if needed

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: npm test
